[package]
name = "rotur-icn-units"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
license.workspace = true
description = "commonly used unit primitives within rotur ICN"
readme = "readme.md"
