[workspace]
resolver = "3"
members = ["rotur-icn-compiler", "rotur-icn-pipeline", "rotur-icn-renderer", "rotur-icn-syntax", "rotur-icn-units", "rotur-icn-viewer"]

[profile.release]
lto = "thin"
strip = "debuginfo"
