[package]
name = "rotur-icn-renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
rotur-icn-compiler = { version = "0.1.0", path = "../rotur-icn-compiler" }
rotur-icn-units = { version = "0.1.0", path = "../rotur-icn-units" }
